### PR TITLE
configure.ac fixups and formatting

### PR DESCRIPTION
**Pull request by uartie**
This series fixes a few minor bugs in configure.ac, cleans up some inconsistent line formatting and adds a summary output at the end of configure.

### CODE REVIEW

**Comment by xuguangxin** [comment]
+1

**Comment by chivakker** [comment]
lgtm +1

**Comment by seanvk** [comment]
lgtm +1, needs verification

**Comment by xuguangxin** [comment]
since we have h264dec and h265enc to merge. So I will merge this after this two components pushed.

**Comment by uartie** [comment]
is this ready to merge?

**Comment by xuguangxin** [comment]
not yet. we will merge this after hevc decoder and encoder merged. 
Sorry for late.

**Comment by xuguangxin** [comment]
hi @uartie , sorry for late. it's merged as 6456e2383dac3a58f1983b7da8ac885b639451a7. thanks for contribute.

**Pull request closed without merging**
