### PR TITLE
use env var for device file to open

### PR DESCRIPTION
**Pull request by jsorg71**

### CODE REVIEW

**Review by xuguangxin — APPROVED** [review]

**Review by uartie — DISMISSED** [review]
LGTM

**Review by uartie — CHANGES_REQUESTED** [review]
Please add "Fixes #809" to commit message

**Comment by uartie** [comment]
@jsorg71 I meant the "git commit message", not the PR title.

**Comment by jsorg71** [comment]
@uartie I don't see that on other commit messages.  Am I missing something?
I do see them, just not on the first line.

**Comment by uartie** [comment]
I think you're looking at the pull-request description/titles... those are different than the actual git commits.  Please reference the issue in the "git commit body".  For example, see https://github.com/01org/libyami/commit/819037fdaafdef7f6234fc22b50d322755d890bf

**Comment by jsorg71** [comment]
got this PR all messed up now, I made a new one #815

**Comment by uartie** [comment]
No problem.  Github PRs can be tricky to get used to... usually you only need to rebase your source branch (i.e. avoid merge updates) and amend commits locally then force push to your upstream branch.  Then PR automatically updates appropriately.

**Pull request closed without merging**
