### PR TITLE
h264dec: check m_currPic before init reference for it

### PR DESCRIPTION
**Pull request by xuguangxin**
this fixes h264 crash issue mentioned in https://github.com/01org/libyami/issues/585

### CODE REVIEW

**Comment by chivakker** [comment]
lgtm :+1:

**Comment by xuguangxin** [comment]
@lizhong1008 help to review,thanks

**Comment by lizhong1008** [comment]
+1

**Comment by xuguangxin** [comment]
merge as 0ad755dd2408fad2710c65ee1b0df7dd08a9cb1b

**Pull request closed without merging**
