### PR TITLE
v4l2 encode support for android surface buffer

### PR DESCRIPTION
**Pull request by halleyzhao**

### CODE REVIEW

**Comment by xuguangxin** [comment]
Please format your patch using https://llvm.org/svn/llvm-project/cfe/trunk/tools/clang-format/git-clang-format
command line:
git-format-clang --style=webkit HEAD^

**Comment by halleyzhao** [comment]
not knowing why it fails

git clang-format --style=webkit HEAD^
usage: git clang-format [OPTIONS] [<commit>] [--] [<file>...]
clang-format: error: unrecognized arguments: -style=webkit -lines=27:27 -lines=42:44 -lines=114:117 -lines=131:134
error: `clang-format v4l2/v4l2_codecbase.h -style=webkit -lines=27:27 -lines=42:44 -lines=114:117 -lines=131:134` failed

**Comment by lizhong1008** [comment]
Hi Halley: which clang-format version you installed?

**Comment by lizhong1008** [comment]
clang-format --h will show supported coding style.

**Comment by xuguangxin** [comment]
Hi Hallye:
you can try use git-clang-format directly instead of "gi clang-format"

**Comment by halleyzhao** [comment]
thanks Zhong/Guangxin
patches have been updated

**Comment by xuguangxin** [comment]
+1

**Comment by xuguangxin** [comment]
merged as 27914b250ccee56a9d6daa3e198b48e0673869c9.
thanks halley

**Pull request closed without merging**
