### PR TITLE
update v4l2codec on android

### PR DESCRIPTION
**Pull request by halleyzhao**

### CODE REVIEW

**Comment by xuguangxin** [comment]
great! +1

**Comment by xuguangxin** [comment]
Hi Halley:
seems it's not build able for
"git clean -dxf && ./autogen.sh --prefix=$LIBYAMI_PREFIX --enable-tests --enable-v4l2  && make -j8 && make install"


"v4l2decode.cpp:67:20: error: ‘typeStrAndroidBufferHandle’ defined but not used [-Werror=unused-variable]
 static const char* typeStrAndroidBufferHandle = "android-buffer-handle";
                    ^
cc1plus: all warnings being treated as errors
make[2]: *** [v4l2decode.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory `/home/thomas/projects/yami/libyami/tests'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/home/thomas/projects/yami/libyami'
make: *** [all] Error 2

**Comment by halleyzhao** [comment]
现在更正了。


抱歉，我本地fix了这个问题，忘了push到github了。

**Comment by halleyzhao** [comment]
is it ok to merge?

**Comment by seanvk** [comment]
@xuguangxin What's the status on this patch?

**Comment by xuguangxin** [comment]
Hi @seanvk 
It's only for android, we should decide it after all Android related things settled.If we do not need support android, maybe we will drop this patch set.

**Comment by xuguangxin** [comment]
close this since we have #522

**Pull request closed without merging**
