### PR TITLE
add user_ptr support on input buffer, save back ioctl command debug string

### PR DESCRIPTION
**Pull request by halleyzhao**

### CODE REVIEW

**Comment by halleyzhao** [comment]
@xuguangxin 
please review and merge it.

**Comment by halleyzhao** [comment]
how about use onEnqueInputBuffer()/inputPuse()/onDequeInputBuffer() func names to replace current acceptInputBuffer()/inputPulse()/recycleInputBuffer()?

similar to output buffer handling funcs

**Comment by halleyzhao** [comment]
halley@halley-braswell:~/yami/libyami$ git diff
diff --git a/v4l2/v4l2_codecbase.cpp b/v4l2/v4l2_codecbase.cpp
index 54ab967..99f8ee0 100644
--- a/v4l2/v4l2_codecbase.cpp
+++ b/v4l2/v4l2_codecbase.cpp
@@ -277,7 +277,7 @@ const char* V4l2CodecBase::IoctlCommandString(long unsigned int command)
     static const char* unknown = "Unkonwn command";
 #define IOCTL_COMMAND_STRING_MAP(cmd)   {cmd, #cmd}
     static struct IoctlCommanMap{
-        long unsigned int command;
+        int command;
         const char* cmdStr;
         } ioctlCommandMap[] = {
             IOCTL_COMMAND_STRING_MAP(VIDIOC_QUERYCAP),

v4l2_codecbase.cpp:298:9: error: narrowing conversion of '2154321408ul' from 'long unsigned int' to 'int' inside { } is ill-formed in C++11 [-Werror=narrowing]
         };

**Comment by xuguangxin** [comment]
ok. +1

**Comment by xuguangxin** [comment]
> how about use onEnqueInputBuffer()/inputPuse()/onDequeInputBuffer() func names to replace current acceptInputBuffer()/inputPulse()/recycleInputBuffer()?
> 
> similar to output buffer handling funcs

it's ok to me

**Comment by xuguangxin** [comment]
merged as 9d324fe686903f8352c920bee778fd6a619cb9b5

**Comment by xuguangxin** [comment]
thanks halley

**Pull request closed without merging**
