### PR TITLE
unittest: vc1, fix mismatch new[] and delete

### PR DESCRIPTION
**Pull request by xuguangxin**

### CODE REVIEW

**Comment by uartie** [comment]
:+1: lgtm

**Comment by chivakker** [comment]
+1 lgtm

**Comment by seanvk** [comment]
lgtm.  needs verified.

**Comment by xuguangxin** [comment]
dongping will help to verify this

**Comment by jayesht** [comment]
Verified this patch with Skylake Linux 4.4.0-24-generic #43-Ubuntu SMP Wed Jun 8 19:27:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux. Ran decode unittest. Patch LGTM.

**Pull request merged**
