### PR TITLE
Revert m_maxCodedbufSize calculation and refine it

### PR DESCRIPTION
**Pull request by lizhong1008**

### CODE REVIEW

**Comment by xuguangxin** [comment]
Could we merge this two commits? it will make sure all commit is build able and run able.
and better you can put gstreamer vaapi's commit id in revert log.

**Comment by lizhong1008** [comment]
yeah, all these two commits can be built, but the first one may can't run well. I'll merge them. Thanks

**Comment by xuguangxin** [comment]
and make sure you can encode a small and a large file before you send pull request again.
thanks.

**Comment by lizhong1008** [comment]
It has beent tested. Don't worry.

**Comment by lizhong1008** [comment]
patch updated.

**Comment by xuguangxin** [comment]
+1

**Pull request closed without merging**
