### PR TITLE
add flags to getOutput method

### PR DESCRIPTION
**Pull request by jsorg71**
Discussed in #206 
This add the ability to pass some flags through libyami for vaPutSurface.

### CODE REVIEW

**Comment by chivakker** [comment]
What is your use case?  shouldn't the de-interlacing flags be set as a parameter to libyami?

**Comment by jsorg71** [comment]
In the referenced issue #206, I explain that sometime BT709 is used on the server.
And yes, since this passes the flags through, you can also use this for de-interlacing flags.

**Comment by chivakker** [comment]
I've checked #206. I also preferred option 2 as it is a cleaner way to handle this such that libva-API is better wrapped within libyami.  

I will let xuguangxin decide if he wants to go forward with this patch instead.

**Comment by xuguangxin** [comment]
hi Daniel:
I think expose more libva is better than wrap it. because following reasons:
1. it's hard to wrap libva. see getOutput for details.
we have 3 getOutput and getOutput(VideoFrameRawData* frame, bool draining = false) have 5  VideoDataMemoryType. it means we have 7 getOuputs. If we want support wayland or android. We need add more getOuput to decoder interface. It's insane. Why not just output VASurfaceID(with some wrapper and reference count, you can see https://github.com/xuguangxin/libyami/commit/f892d1f8faddb2e7964e89a875c438ec87b305e0 for detials), user can do what he want. dump, output to x,output to wayland, It's his call.

2. wrap libva is not making things easier. 
I mean call
    virtual Decode_Status getOutput(unsigned long draw, int64_t *timeStamp
        , int drawX, int drawY, int drawWidth, int drawHeight, bool draining = false
        , int frameX = -1, int frameY = -1, int frameWidth = -1, int frameHeight = -1) = 0; 
is not easier than call getOutput and  vaPutSurface.
You still need prepare all params.

3. wrap libva will lost flexibility.
what if some one still need   cliprects in vaPutSurface. Do we need more params to getOuptut?

I want keep yami decoder module more simpler. Just accept bitstream and output surface. Let other module do vpp,output, and file dump things.  I can talk to you more details about this when we meet face to face.
thanks.

**Comment by jsorg71** [comment]
xuguangxin,

That is perfectly acceptable.
I think you should reject my patch and remove X11 support from libyami.
It's just confusing if there is X11 support but limited.
I can change my code to use libyami for decode and libva for render.

Jay

**Comment by xuguangxin** [comment]
Hi Jay:
Sorry for late response. I am in a business trip. Only have limited access to email. 
Remove X dependency is not gone happen very quickly. Because yami decodeer/encoder and v4l2 decoder/encoder dependent  on this.
Is it ok to merge your patch to master? It can meet your current requirement. And you can change you code when we removed X in libyami?
thanks

**Comment by jsorg71** [comment]
Sure, if it looks useful.

**Comment by jsorg71** [comment]
I have working the va render path and only yami for decode.
I only found a small 'const' missing capi error.  I'll do a pull request for that.
I think we can delete this PR.

**Pull request closed without merging**
