### PR TITLE
add 10 bits decoder to hevc.

### LINKED ISSUE #624: HEVC 10 bits decoder
Support HEVC 10bits in libyami, this is gap between libva and libyami

### PR DESCRIPTION
**Pull request by xuguangxin**
this will fix #624

### CODE REVIEW

**Comment by xuguangxin** [comment]
@YuJiankang, Please help to review

**Comment by YuJiankang** [comment]
lgtm, +1

**Comment by lizhong1008** [comment]
LGTM, but would better we can add some commit message for 3d3380a516fb41f4ad388d0faa2096eb8097c17e

**Comment by xuguangxin** [comment]
What I should put in, I think commit title is very clear

**Comment by lizhong1008** [comment]
@xuguangxin 
1. I think we would better can avoid a NULL commit message in most cases.
2. Here we are mainly expose VAProfileHEVCMain10 profile, not add a new decoder named hevc 10 bits. It can be specified in the commit message.

**Comment by xuguangxin** [comment]
@lizhong1008
1.  this is not a null commit log, just null body, the body of commit message is optional. 
You can check http://supercollider.github.io/development/commit-messagee  and http://chris.beams.io/posts/git-commit/. `1. Separate subject from body with a blank line`
2. I can update this

**Comment by xuguangxin** [comment]
@lizhong1008 , update.

**Comment by lizhong1008** [comment]
@xuguangxin thanks for the explanation and update. 
Yeah, if the patch is simple enough and the commit title can cover all information , no need commit body, else it is needed.

**Comment by lizhong1008** [comment]
+1

**Comment by wudping** [comment]
verify + 1

**Comment by wudping** [comment]
verify - 1,
I am sorry for this. Because I test it on a new KBL platform, the platform is not setup completely. I double check it, find out that the HEVC 10bit depth decoding is okay, but these patches make new problem with 8 bit depth decoding.

**Comment by xuguangxin** [comment]
close this since we have https://github.com/01org/libyami/pull/647

**Pull request closed without merging**
