### PR TITLE
delete yuv file.

### PR DESCRIPTION
**Pull request by luokunrock**
Signed-off-by: Luo Kun <kun.luo@intel.com>

### CODE REVIEW

**Comment by halleyzhao** [comment]
please change the author name by:
   git config --global user.ame "Your Name"
   git config --global user.email "mail@xxx"

**Comment by luokunrock** [comment]
ok, the author name is now correct. Pls check again.

**Comment by halleyzhao** [comment]
+1

**Comment by xuguangxin** [comment]
merged as 95fb82c753ab2e765f1e1e11d3203f645a95a974

**Pull request closed without merging**
