### PR TITLE
add two advanced deinterlace mode motion_adaptive and motion_compensated

### PR DESCRIPTION
**Pull request by xuguangxin**

### CODE REVIEW

**Comment by xuguangxin** [comment]
@uartie , please help review this.
I found the media-driver and intel-vappi-driver have different behaviors.
media-driver will fallback to spacial deinterlace if we just give him one frame.
Intel -vaapi driver will simply silent failed with no error returned since he needs a forward reference frame
My first patch only tested on media-driver. 
so I write a new one. it set forward reference frame.  should work on both drivers. 
thanks

**Comment by uartie** [comment]
@xuguangxin please fix travis-ci build first.

**Comment by xuguangxin** [comment]
@uartie , done, thanks for reminding.

**Review by uartie — APPROVED** [review]
LGTM

**Pull request merged**
