### PR TITLE
Add HEVC CBR support

### PR DESCRIPTION
**Pull request by lizhong1008**

### CODE REVIEW

**Comment by xuguangxin** [comment]
+1

**Comment by YuJiankang** [comment]
+1

**Comment by seanvk** [comment]
lgtm, but I would like to see verified by QA if possible.

**Comment by xuguangxin** [comment]
Yes. QA is testing zhong's patch. this why we did not commit to master yet.

**Comment by FocusLuo** [comment]
@seanvk  QA ETA to give out the test result in this week(WW51).

**Comment by xuguangxin** [comment]
merged as 8bd22c76950fe0034d54e33bc7f71535f6d2e72f. thanks Sean & Focus

**Pull request closed without merging**
