### PR TITLE
h264dec: fix a potential complie error

### PR DESCRIPTION
**Pull request by lizhong1008**
this patch is to fix https://github.com/01org/libyami/issues/351

### CODE REVIEW

**Comment by xuguangxin** [comment]
why we need this. This seems same to me

**Comment by lizhong1008** [comment]
why same?

**Comment by xuguangxin** [comment]
== have higher priority. So it always evaluate == then ?:

**Comment by xuguangxin** [comment]
add "()" or not is same thing,I think.

**Comment by lizhong1008** [comment]
sorry, I mix the priority of "=" with "==".

**Pull request closed without merging**
