### PR TITLE
common: init width and height

### PR DESCRIPTION
**Pull request by wudping**
assign the initial values into width and height in function setFormat().

Signed-off-by: wudping <dongpingx.wu@intel.com>

### CODE REVIEW

**Comment by wudping** [comment]
please help to review, thanks in advance.

**Comment by xuguangxin** [comment]
please add some comments on this like fix what problem.
thanks

**Comment by wudping** [comment]
thanks @xuguangxin , 
If not, the size of decoded YUV file will be 0.

**Comment by wudping** [comment]
added comment in commit message, thanks @xuguangxin .

**Pull request merged**
