### PR TITLE
v4l2: fix crash when v4l2Decode exits

### PR DESCRIPTION
**Pull request by hongbog**
- add sync mode support for workThread and thread which ioctl(VIDIOC_REQBUFS) method is in

### CODE REVIEW

**Comment by halleyzhao** [comment]
+1 @xuguangxin

**Comment by xuguangxin** [comment]
Hi hongbog:
Could you use your company's email to submit this patch? So we can track the patch origin.
thanks.

**Comment by halleyzhao** [comment]
+1 @xuguangxin

**Comment by xuguangxin** [comment]
+1

**Comment by xuguangxin** [comment]
merged as fe207940148db667aca6a822ba197f1b2e6aae00. thanks hongbo and halley

**Pull request closed without merging**
