### PR TITLE
simple player and new getOutput interface for decoder.

### PR DESCRIPTION
**Pull request by xuguangxin**
1. add simple player to demo decoder API usage.
2. add SharedPtr<VideoFrame> getOutput to decoder interface. hope we can use this single getOutput to replace other 7.

### CODE REVIEW

**Comment by uartie** [comment]
/simply/simple/
/getOuptut/getOutput/
/inteface/interface/

**Comment by xuguangxin** [comment]
changed according to uartie's comment

**Comment by YuJiankang** [comment]
+1

**Comment by xuguangxin** [comment]
merged as 66c282bf669d0e6edb17fc5674d3b94e2f66e029

**Pull request closed without merging**
