### PR TITLE
Fix permissions on source files

### LINKED ISSUE #391: Source files are marked executable
Source files should not be marked executable.

### PR DESCRIPTION
**Pull request by scott-d-phillips**
Source files should not be executable.

 find . \( -name \*.h -o -name \*.cpp -o -name \*.cc -o -name \*.c \
 -o -name \*.am -o -name \*.ac \) -perm /u+x -exec chmod a-x {} \;

Fixed #391

Signed-off-by: Scott D Phillips <scott.d.phillips@intel.com>

### CODE REVIEW

**Comment by uartie** [comment]
lgtm

**Comment by chivakker** [comment]
lgtm :+1:

**Comment by xuguangxin** [comment]
+1

**Comment by xuguangxin** [comment]
merged as 4c659e22f38f7c560cc36380a13bbf76a11dffc3.
thanks Phillips, U.Artie and Daniel.

**Pull request closed without merging**
