### PR TITLE
add decode api test for h264

### PR DESCRIPTION
**Pull request by xuguangxin**
To fix format change issues, we need many patch set. So I just submit h264 related things first. To make review's life easier. This is exactly same thing as https://github.com/01org/libyami/pull/658, but removed mpeg2 patch.

### CODE REVIEW

**Comment by wudping** [comment]
verify + 1

**Comment by wudping** [comment]
verify - 1, H265 clips has regression. Sorry for last verify.

**Comment by xuguangxin** [comment]
Hi @wudping , thanks for find this issue. updated, please help to verify again.

**Comment by wudping** [comment]
verify + 1

**Comment by YuJiankang** [comment]
lgtm, +1

**Review by YuJiankang — APPROVED** [review]

**Pull request merged**
