### PR TITLE
yamiinfo

### PR DESCRIPTION
**Pull request by uartie**
Add yamiinfo binary to tests.  This is useful for getting yami version and supported codec mime type class info.

### CODE REVIEW

**Comment by uartie** [comment]
@xuguangxin patch is updated per your good suggestion... cheers.

**Comment by xuguangxin** [comment]
Great! thanks for your quick response. I just tagged 0.3.1 release. Let use merge this after 0.3.1 final released

**Comment by chivakker** [comment]
lgtm

**Comment by seanvk** [comment]
lgtm

**Comment by uartie** [comment]
FYI, this patch and #396 may conflict with each other

**Comment by xuguangxin** [comment]
no problem, we will fix it.

**Comment by xuguangxin** [comment]
merged as b95d0868492cf7f3adcecf68e79de3c7a4c7cb70
thanks all

**Pull request closed without merging**
